### ISSUE TITLE
Update to use the official OpenCOR+Python snapshot

### ISSUE THREAD

**Issue by agarny** [hsorby/docker_opencor_run_model#5]
Python support has recently been officially added to OpenCOR. So, rather than referencing and using https://github.com/dbrnz/opencor/releases/download/snapshot-2019-06-11/OpenCOR-2019-06-11-Linux.tar.gz, we should now be using https://github.com/opencor/opencor/releases/download/snapshot-2019-12-20/OpenCOR-2019-12-20-Linux.tar.gz. We should also update the `run_model.py` script to use our updated Python module and wrappers.

Ping @hsorby and @nickerso.

**Comment by nickerso** [comment]
fixed by #6

**Comment by nickerso** [comment]
except the snapshot releases are not available on github...

**Comment by agarny** [comment]
Hmm... indeed, they are not. Only the official releases are. Still, you can get it from https://opencor.ws/downloads/snapshots/2020-02-14/OpenCOR-2020-02-14-Linux.tar.gz.
